### ISSUE TITLE
Sudo not working in chroot on P7P

### ISSUE THREAD

**Issue by matejdro** [Magisk-Modules-Alt-Repo/chroot-distro#5]
When attempting to use `sudo` inside chrooted system (notably `archlinux`), `sudo` command is broken, complaining about

`effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`

I guess this has to do something with the way Android mounts `/data`?  The device is Pixel 7 Pro.

**Comment by matejdro** [comment]
Yes, that worked, thanks!

Although I feel it is a bad idea to do a global remount since that affects the entire Android instead of just the chroot instance. Presumably there is no better solution?

**Comment by gixousiyq** [comment]
Sorry for the late response 
su -c remounts /data for the running proccess only E.g termux
To remount /data for all the system you have to add -mm to the command to force it into global mount space
su -mm -c mount...

**Comment by jjkola** [comment]
My solution to this was to format external sd card with ext4 and then transfer files/folders from `/data/local/chroot-distro` to newly formatted SD card, and then mounting it at that folder with Termux:boot (unfortunately it sometimes does not work, and I have to manually run the scripts). This has the added benefit of not making taking space from internal storage. If this solution is used then you can't allow android to format the SD card and you will not be able to access it from android side. As I will not be using the android side at all (other than for administrating the tablet) this is perfectly okay with me, but your mileage may wary.

**Comment by jjkola** [comment]
Reopening this to document the problem and solutions so that others can avoid this.

**Comment by gixousiyq** [comment]
I think a better way to solve this problem is to make the script run su -c mount -o remount,dev,suid /data every mount, This should fix the problem without needing to use external storage or any workaround's

By the way you can also make a virtual disk and format it as ext4 and mount it into ```/data/local/chroot-distro``` by running these:
```sh
su -c truncate -S 15G /data/local/distros.img
```
The above will create a disk image in ```/data/local``` with the size 15 Gigabyte's, Change it to the size you want
```sh
su -c mke2fs -t ext4 /data/local/distros.img
```
The above will put a ext4 filesystem on our virtual disk
```sh
su -c mount /data/local/distros.img /data/local/chroot-distro
```
The above will mount our disk image to ```/data/local/chroot-distro```, Now our distros are housed in a ext4 filesystem separate from our main filesystem
But keep in mind that this will take space from internal storage and it may be complicated to resize this disk image, Just an idea I wanted to share.

**Comment by jjkola** [comment]
@gixousiyq Thanks for the pointers. I'll create a PR for this and would like it if you could help reviewing it.

**Comment by jjkola** [comment]
@gixousiyq Any chance of reviewing the change? If you can't comment on the PR then could you please add your comments here so I can finish this?

**Comment by gixousiyq** [comment]
Sorry didnt see it :)

**Comment by jjkola** [comment]
No problem.
